title: Dennis Hauser # your name (or website title) here
logo: "/images/photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Data Analyst with passion for the automotive field, dedicated to uncovering valuable insights from data.
  Master of science in Machine Learning and Data Analytics with focusing in my thesis on Large Language Models.
  <br><br>
  <a href="https://www.linkedin.com/in/dennis-hauser-2627021a6/" target="_blank" rel="noopener norefferrer">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
